version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Preparing for the build..."
      - dir # Debug: List files
      - echo "Checking Java version..."
      - java -version
      - echo "Listing files in the root directory:"
      - ls -la
      - echo "Building the project with Gradle..."
      - ./gradlew clean build
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=381492308048.dkr.ecr.us-east-1.amazonaws.com/boa-user-registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin %REPOSITORY_URI%
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on %date% %time%
      - echo Building the Docker image...
      - docker build -t %REPOSITORY_URI%:latest .
      - docker tag %REPOSITORY_URI%:latest %REPOSITORY_URI%:%IMAGE_TAG%
  post_build:
    commands:
      - echo Build completed on %date% %time%
      - echo Pushing the Docker images...
      - docker push %REPOSITORY_URI%:latest
      - docker push %REPOSITORY_URI%:%IMAGE_TAG%
      - echo Writing image definitions file...
      - printf '[{"name":"user-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Writing image definitions file...
      - # add your container name
      - DOCKER_CONTAINER_NAME=boa-user-registry
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo %DOCKER_CONTAINER_NAME%
      - echo Printing imagedefinitions.json...
      - type imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - build\libs\*.jar # Windows path for Gradle's default JAR output